### ISSUE TITLE
Updated tokens are not committed to the DB when refreshing

### ISSUE THREAD

**Issue by aGHz** [python-social-auth/social-storage-sqlalchemy#2]
The following code does not update the appropriate `extra_data` in the database:

```py
from flask import g
from social_flask.utils import load_strategy

...

user_auth = g.user.social_auth.filter_by(provider='google-oauth2').first()
strategy = load_strategy()
user_auth.refresh_token(strategy)
```

Some debugging shows that [`UserMixin.set_extra_data`](https://github.com/python-social-auth/social-core/blob/feeb27c5d2bdf94428d09f289342cd64a679df62/social_core/storage.py#L102) is getting called with all the appropriate data and is itself calling `extra_data.update` properly, but the modification doesn't getting picked up by SQLAlchemy (it doesn't appear in `session.dirty` and `self._sa_instance_state` doesn't have `modified` set to `True`).

This is because [`MutableDict.as_mutable`](https://github.com/zzzeek/sqlalchemy/blob/fa6dd376bb24845724287d980a98ea50eb1cfab1/lib/sqlalchemy/ext/mutable.py#L553) checks column types [by object identity](https://github.com/zzzeek/sqlalchemy/blob/fa6dd376bb24845724287d980a98ea50eb1cfab1/lib/sqlalchemy/ext/mutable.py#L589), while SQLAlchemy [copies columns](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/mixins.html#mixing-in-columns) inherited from mixins. The result is that `MutableDict` fails to attach all the event listeners to the column property in the mapper, and changes don't get noticed.

The solution is to declare the `extra_data` column using `@declared_attr` in `SQLAlchemyUserMixin`.

**Comment by ddoskind** [comment]
I just stumbled upon the same problem (sadly didn't check here first), and @aGHz's explanation and fix is spot on. See http://stackoverflow.com/questions/42908662/mutable-column-from-mixin-does-not-track-mutation
